name: ecofier_viz
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
   sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dartz: ^0.10.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  loading_animation_widget: ^1.3.0
  http: ^1.4.0
  get_it: ^8.0.3
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/core/assets/
